id: I6BE96C3E
ocr_import_info:
  timestamp: '2024-12-12T06:25:39.869424+00:00'
  batch_id: batch-8d8c
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: OpenPecha
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.13
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-12-12 06:37:06.407080+00:00
last_modified: 2024-12-12 06:37:06.407086+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W19351
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW19351
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བདེ་ཆེན་སྨོན་ལམ་གྱི་འབྱེད་འགྲེལ།
  languages:
  - bo
  author: ཐུགས་རྗེ་གཞན་ཕན་དཔལ་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.9179987358894461
  ocr_word_median_confidence_index: 0.9753314550000001
bases:
  I00EGS1016861:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016861
      total_pages: 140
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00EGS1016861.txt
    statistics:
      ocr_word_median_confidence_index: 0.9753314550000001
      ocr_word_mean_confidence_index: 0.9179987358894461
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
